#FROM node:latest
FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN mkdir -p /usr/src/app/audios

RUN npm install

COPY . .

EXPOSE 4000

#CMD ["node", "server.js"]
CMD ["npm", "run", "dev"]